# Generated by Django 5.1.15 on 2026-02-27 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area_sq_miles', models.DecimalField(decimal_places=3, max_digits=7)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='proposals.borough')),
            ],
            options={
                'ordering': ['borough', 'name'],
                'unique_together': {('borough', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('lot_size_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_units', models.IntegerField()),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('projected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('feasibility_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 computed feasibility score', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='proposals.neighborhood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=150)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='proposals.proposal')),
            ],
            options={
                'verbose_name_plural': 'Proposal status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoningDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('manufacturing', 'Manufacturing'), ('mixed', 'Mixed Use')], max_length=20)),
                ('max_far', models.DecimalField(decimal_places=2, help_text='Maximum Floor Area Ratio', max_digits=5)),
                ('max_height_ft', models.IntegerField()),
                ('residential_allowed', models.BooleanField(default=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoning_districts', to='proposals.neighborhood')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('median_sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('median_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacancy_rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('permits_issued', models.IntegerField()),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='proposals.neighborhood')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('neighborhood', 'period')},
            },
        ),
        migrations.CreateModel(
            name='DemographicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('population', models.IntegerField()),
                ('median_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('population_growth_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transit_score', models.DecimalField(decimal_places=1, help_text='0-100 transit accessibility score', max_digits=4)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='proposals.neighborhood')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('neighborhood', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FinancialProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cumulative_roi', models.DecimalField(decimal_places=2, max_digits=7)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_projections', to='proposals.proposal')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('proposal', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ProposalUnitMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('studio', 'Studio'), ('1br', '1 Bedroom'), ('2br', '2 Bedroom'), ('3br', '3 Bedroom'), ('4br', '4+ Bedroom')], max_length=10)),
                ('count', models.IntegerField()),
                ('avg_sqft', models.DecimalField(decimal_places=2, max_digits=8)),
                ('projected_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_mix', to='proposals.proposal')),
            ],
            options={
                'unique_together': {('proposal', 'unit_type')},
            },
        ),
    ]
