# Generated by Django 5.1.15 on 2026-02-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('neighborhood_id', models.IntegerField()),
                ('neighborhood_name', models.CharField(max_length=100)),
                ('period', models.DateField()),
                ('median_sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('median_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_change_pct', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('rent_change_pct', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'vw_MarketTrends',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodRanking',
            fields=[
                ('neighborhood_id', models.IntegerField(primary_key=True, serialize=False)),
                ('neighborhood_name', models.CharField(max_length=100)),
                ('borough_name', models.CharField(max_length=50)),
                ('median_sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('median_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacancy_rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('population', models.IntegerField()),
                ('median_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transit_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('development_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('overall_rank', models.IntegerField()),
                ('quartile', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_NeighborhoodRankings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalDashboardSummary',
            fields=[
                ('borough_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_proposals', models.IntegerField()),
                ('total_units', models.IntegerField()),
                ('avg_feasibility_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_projected_revenue', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'db_table': 'vw_ProposalDashboardSummary',
                'managed': False,
            },
        ),
    ]
